### ISSUE TITLE
Unable to use LF Tools in QGIS 3.32.2 Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by kennorris49** [LEOXINGU/lftools#10]
Couldn't load plugin 'lf tools' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'PIL' 

I'm a rank amateur at this so please be patient and thanks, prospectively, for the plugin.

**Comment by LEOXINGU** [comment]
This problem is happening because your QGIS is being installed missing the PIL package (from Pillow), but it can be resolved.
Install Pillow through the OSGeo Shell using the command:
python3 -m pip install Pillow==8.4.0
Note: You must run as administrator.
If you have any questions about the execution, feel free to ask me.

**Comment by kennorris49** [comment]
Many thanks but I think I had Pillow 10.0.1 installed already. Your kind
suggestion removed that and installed 8.4.0
But my problems with QGIS, self-inflicted, are now quite deep and nothing
to do with you input.
